name: Terraform apply infra change - e2e-IacProfile-102fa648-3c1a-49dc-b72c-2461748b9c07

on:
  push:
    branches: ["main"]

jobs:
  QA-placeholder:
    name: QA
    needs: [dev-placeholder]
    runs-on: ubuntu-latest
    steps:
      - run: echo "running QA stage"
  dev-placeholder:
    name: dev
    needs: []
    runs-on: ubuntu-latest
    steps:
      - run: echo "running dev stage"
  Prod-placeholder:
    name: Prod
    needs: [QA-placeholder]
    runs-on: ubuntu-latest
    steps:
      - run: echo "running Prod stage"
