name: Terraform apply infra change - e2e-IacProfile-346b178b-9de0-4d5e-9655-103f96fe248f

on:
  push:
    branches: ["main"]

jobs:
  dev-placeholder:
    name: dev
    needs: []
    runs-on: ubuntu-latest
    steps:
      - run: echo "running dev stage"
  Prod-placeholder:
    name: Prod
    needs: [QA-placeholder]
    runs-on: ubuntu-latest
    steps:
      - run: echo "running Prod stage"
  QA-placeholder:
    name: QA
    needs: [dev-placeholder]
    runs-on: ubuntu-latest
    steps:
      - run: echo "running QA stage"
