name: Terraform apply infra change - e2e-IacProfile-72064538-aea0-46c5-9bb3-d67599a58c00

on:
  push:
    branches: ["main"]

jobs:
  Prod-placeholder:
    name: Prod
    needs: [QA-placeholder]
    runs-on: ubuntu-latest
    steps:
      - run: echo "running Prod stage"
  QA-placeholder:
    name: QA
    needs: [dev-placeholder]
    runs-on: ubuntu-latest
    steps:
      - run: echo "running QA stage"
  dev-placeholder:
    name: dev
    needs: []
    runs-on: ubuntu-latest
    steps:
      - run: echo "running dev stage"
