name: Terraform apply infra change - e2e-IacProfile-2510db0a-1ae1-41b5-8e80-80f3b85f1bec

on:
  push:
    branches: ["main"]

jobs:
  dev-placeholder:
    name: dev
    needs: []
    runs-on: ubuntu-latest
    steps:
      - run: echo "running dev stage"
  Prod-placeholder:
    name: Prod
    needs: [QA-placeholder]
    runs-on: ubuntu-latest
    steps:
      - run: echo "running Prod stage"
  QA-placeholder:
    name: QA
    needs: [dev-placeholder]
    runs-on: ubuntu-latest
    steps:
      - run: echo "running QA stage"
