name: Terraform apply infra change - e2e-IacProfile-07e9ef8b-011f-4d25-8872-2e5d661a2d67

on:
  push:
    branches: ["main"]

jobs:
  dev-placeholder:
    name: dev
    needs: []
    runs-on: ubuntu-latest
    steps:
      - run: echo "running dev stage"
  Prod-placeholder:
    name: Prod
    needs: [QA-placeholder]
    runs-on: ubuntu-latest
    steps:
      - run: echo "running Prod stage"
  QA-placeholder:
    name: QA
    needs: [dev-placeholder]
    runs-on: ubuntu-latest
    steps:
      - run: echo "running QA stage"
